// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// Generate Prisma Client based on your introspected schema:
// npx prisma generate
//
// update db with schema changes:
// npx prisma migrate dev

import * as dotenv from "dotenv";
dotenv.config();

import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: 'tsx prisma/seed.ts',
  },
  datasource: {
    url: env("DATABASE_URL")
  },
});
