import type { Metadata } from "next";
import "./globals.css";
import { Footer } from "@/components/Footer/Footer";
import { TopBarNavigation } from "../components/Menu/TopBarNavigation";

export const metadata: Metadata = {
  title: "ONG Violeta Eliz",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className="w-full overflow-x-hidden desktopXLarge:w-[1444px] desktopXLarge:ml-auto mr-auto">
        <TopBarNavigation />
        {children}
        <Footer />
      </body>
    </html>
  );
}
